on: [push, pull_request]

name: ci

jobs:
  test:
    name: clippy + tests + docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: r7kamura/rust-problem-matchers@v1

      - name: run CI checks
        run: bash scripts/ci.sh test
        shell: bash

  rustfmt:
    name: rustfmt (nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: r7kamura/rust-problem-matchers@v1

      - name: run CI checks
        run: bash scripts/ci.sh rustfmt
        shell: bash
